#!/usr/bin/python3
# Returns a list of all māori words and tells the user what percentage of words are considered 'english' or 'māori'

import re
import sys
import argparse

from taumahi import auaha_kupu_tūtira, poro_tūtira


def tangohia_kupu_tōkau(args):
    kōnae = open(args.input, 'r')
    kupu_tōkau = kōnae.read()
    kōnae.close()
    return kupu_tōkau


def tuhi_puta_tuhinga(args, kupu_hou):
    # writes the list of words to a new document, each word and hyphenated word on a new line
    kupu_tūtira_hou = open(args.output, "w")
    kupu_tūtira_hou.write("\n".join(kupu_hou))
    kupu_tūtira_hou.close()


def matua():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        '--input', '-i', help="Input multilanguage corpus text file")
    parser.add_argument(
        '--output', '-o', help="Output text file where words that are considered to be Māori are stored")

    args = parser.parse_args()
    kupu_tōkau = tangohia_kupu_tōkau(args)
    kupu_tūtira_pīki = auaha_kupu_tūtira(kupu_tōkau)
    kupu_hou = poro_tūtira(kupu_tūtira_pīki)
    tuhi_puta_tuhinga(args, kupu_hou)


if __name__ == '__main__':
    matua()
